plugins:
  - rubocop-rails
  - rubocop-rspec_rails
require:
  - rubocop-rails
  - rubocop-rspec_rails

Bundler/OrderedGems:
  Enabled: true

Metrics/BlockLength:
  Exclude: 
    - '**/*_spec.rb'
    - 'Guardfile'
    - '**/*.rake'
    - 'db/migrate/**'
Metrics/MethodLength:
  Max: 25
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Exclude:
    - 'app/controllers/v1/concerns/authenticator.rb'
Rails/UniqueValidationWithoutIndex:
  Enabled: false