services:
  postgres:
    image: postgres:17
    container_name: e-shop-db
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker123
  redis:
    image: redis:7.4.2
    container_name: e-shop-redis
    ports:
      - 6379:6379
volumes:
  db-data: